<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="_FinalizedOrder\**" />
    <EmbeddedResource Remove="_FinalizedOrder\**" />
    <None Remove="_FinalizedOrder\**" />
  </ItemGroup>

	<ItemGroup>
		<PackageReference Include="CryptoPrice" Version="0.0.3" />
		<PackageReference Include="Nethereum.JsonRpc.WebSocketClient" Version="5.0.0" />
		<PackageReference Include="Nethereum.RPC.Reactive" Version="5.0.0" />
		<PackageReference Include="Nethereum.Accounts" Version="5.0.0" />
		<PackageReference Include="Nethereum.Web3" Version="5.0.0" />
		<PackageReference Include="Nethereum.Signer" Version="5.0.0" />
		<PackageReference Include="Nethereum.Contracts" Version="5.0.0" />
		<PackageReference Include="Microsoft.AspNetCore.SignalR.Core" Version="1.2.0" />
		<PackageReference Include="System.Net.WebSockets" Version="4.3.0" />
		<PackageReference Include="System.Reactive" Version="6.0.1" />
	</ItemGroup>


	<ItemGroup>
    <ProjectReference Include="..\RZPrime.Domin\RZPrime.Domain.csproj" />
  </ItemGroup>

</Project>
